[project]
name = "building-etl-pipelines-with-python-book"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Alvaro Robles", email = "alvarorobleses@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "certifi>=2026.7.22",
    "lxml>=6.1.1",
    "matplotlib>=3.11.1",
    "numpy>=2.5.1",
    "pandas>=3.0.5",
    "pandas-stubs~=3.0.5",
    "pyarrow>=25.0.0",
    "requests>=2.34.2",
    "urllib3>=2.7.0",
]

[project.scripts]
building-etl-pipelines-with-python-book = "building_etl_pipelines_with_python_book:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
